# Generated by Django 4.2.4 on 2023-11-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0028_rename_modeofpreapartion_review_modeofpreparation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeeimages',
            name='committee_image',
            field=models.FileField(null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='conferenceimages',
            name='conference_image',
            field=models.FileField(null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='file',
            field=models.FileField(upload_to='paper/'),
        ),
    ]
